import { BrowserStorage } from '../core/storage.js';
import { PresetManager } from '../components/preset-manager.js';
import { CodeBlock } from '../components/code-block.js';

const $=(s,r=document)=>r.querySelector(s);
const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const storage=new BrowserStorage(localStorage,{prefix:'nlab-review:'});

const svg={
  close:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round"><path d="M6 6l12 12M18 6 6 18"/></svg>',
  menu:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M5 7h14M5 12h14M5 17h14"/></svg>',
  info:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="9"/><path d="M12 11v6M12 7h.01"/></svg>',
  phone:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="7" y="2" width="10" height="20" rx="2"/><path d="M10 18h4"/></svg>',
  tablet:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="5" y="2" width="14" height="20" rx="2"/><path d="M11 18h2"/></svg>',
  desktop:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="4" width="18" height="13" rx="1"/><path d="M8 21h8M12 17v4"/></svg>',
  rotate:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M20 7V3l-3 3a8 8 0 1 0 2 8"/></svg>'
};

function style(){
  const el=document.createElement('style');
  el.textContent=`
  .review-info{display:inline-flex;align-items:center;gap:.35rem;margin-left:.45rem;padding:.18rem .42rem;border:1px solid currentColor;border-radius:999px;background:transparent;font-size:.72rem;vertical-align:middle;cursor:pointer}
  .review-info svg,.review-icon svg{width:1rem;height:1rem;display:block}.review-id{font:600 .68rem/1 ui-monospace,monospace;opacity:.72}
  .review-subhead{display:flex;align-items:center;gap:.35rem;flex-wrap:wrap}.review-toolbar{display:flex;gap:.45rem;align-items:center;flex-wrap:wrap;padding:.55rem;border:1px dashed var(--nlab-border,#94a3b8);border-radius:.65rem;margin:.4rem 0}
  .review-toolbar label{display:inline-flex;gap:.3rem;align-items:center}.review-segment{display:inline-flex;border:1px solid var(--nlab-border,#94a3b8);border-radius:.55rem;overflow:hidden}.review-segment button{border:0;border-right:1px solid var(--nlab-border,#94a3b8);border-radius:0}.review-segment button:last-child{border-right:0}.review-segment button.is-active{outline:2px solid var(--nlab-accent,#2563eb);outline-offset:-2px;font-weight:700}
  .review-slider{display:grid;grid-template-columns:auto minmax(120px,1fr) auto;gap:.4rem;align-items:center}.review-preset-zone{border-top:1px dashed var(--nlab-border,#94a3b8);padding-top:.6rem;margin-top:.6rem}.review-scope button.is-active{font-weight:700;outline:2px solid var(--nlab-accent,#2563eb)}
  html[data-nav-start='below-header'] .demo-nav{top:var(--review-header-height,58px)!important;max-height:calc(100vh - var(--review-header-height,58px))!important}.demo-nav-head #nav-toggle svg{width:1rem!important;height:1rem!important}.demo-nav-head #nav-toggle{padding:.3rem!important}
  .review-toast{position:fixed;right:1rem;bottom:1rem;z-index:99999;padding:.55rem .8rem;border-radius:.55rem;background:#111827;color:#fff;box-shadow:0 8px 30px #0004;opacity:0;transform:translateY(8px);transition:.18s}.review-toast.show{opacity:1;transform:none}
  .review-data-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:.5rem}.review-data-card{border:1px solid var(--nlab-border,#94a3b8);border-radius:.55rem;padding:.55rem}.review-data-card strong{display:block}.review-json-diff{display:grid;grid-template-columns:1fr 1fr;gap:.7rem}.review-json-diff pre{white-space:pre-wrap}.review-added{background:#22c55e22}.review-removed{background:#eab30822}.review-changed{background:#3b82f622}
  .nlab-floating-panel[data-review-compact='true'] .nlab-floating-panel__body,.nlab-floating-panel[data-review-compact='true'] .nlab-floating-panel__resize{display:none}.nlab-floating-panel[data-review-compact='true']{height:auto!important;min-height:0!important}.panel-actions{display:flex;gap:.25rem;margin-left:auto}.panel-actions button{flex:0 0 auto}.panel-actions .danger{color:#dc2626}
  `;
  document.head.append(el);
}
function toast(text){let n=$('.review-toast');if(!n){n=document.createElement('div');n.className='review-toast';document.body.append(n);}n.textContent=text;n.classList.add('show');clearTimeout(n._t);n._t=setTimeout(()=>n.classList.remove('show'),1800);}

function openInfo(id,title,body){const panel=$('#panel');if(!panel)return;panel.hidden=false;const help=$('#help-content');if(help)help.innerHTML=`<h3>${title}</h3><p><code>${id}</code></p>${body}`;}
function decorateSubsections(){let seq=1;for(const root of $$('#demo-content .demo-panel,#demo-content .demo-subpanel')){const h=$(':scope > h3,:scope > strong',root);if(!h||h.querySelector('.review-info'))continue;const id=`DMO-SUB-${String(seq++).padStart(3,'0')}`;root.dataset.nlabId=id;const wrap=document.createElement('span');wrap.className='review-subhead';const btn=document.createElement('button');btn.type='button';btn.className='review-info';btn.title=`${id} — informations et test`;btn.innerHTML=`${svg.info}<span class="review-id">${id}</span>`;btn.addEventListener('click',()=>openInfo(id,h.textContent.trim(),'<p>Cette sous-section est testable indépendamment. Vérifiez ses contrôles, son résultat visuel et sa portée.</p>'));h.append(btn);}
}

function enhanceNav(){const tools=$('.demo-nav-tools');if(!tools)return;const mode=document.createElement('label');mode.title='Position verticale de départ du sommaire';mode.innerHTML='Départ <select id="review-nav-start"><option value="top">Haut de page</option><option value="below-header">Sous le header</option></select>';tools.append(mode);const select=$('#review-nav-start');select.value=storage.get('nav-start','top');const apply=()=>{document.documentElement.dataset.navStart=select.value;storage.set('nav-start',select.value);const hh=$('.demo-header')?.getBoundingClientRect().height||58;document.documentElement.style.setProperty('--review-header-height',`${Math.round(hh)}px`);};select.addEventListener('change',apply);apply();
  const toggle=$('#nav-toggle');const update=()=>{const collapsed=$('#side-nav')?.classList.contains('is-collapsed');toggle.innerHTML=collapsed?svg.menu:svg.close;toggle.title=collapsed?'Afficher le sommaire':'Masquer le sommaire';};toggle?.addEventListener('click',()=>setTimeout(update,0));$('#summary-toggle')?.addEventListener('click',()=>setTimeout(update,0));update();
}

function scopeControl(panel,id){const bar=document.createElement('div');bar.className='review-toolbar review-scope';bar.innerHTML='<strong>Portée :</strong><button data-scope="global" class="is-active">Global</button><button data-scope="type">Même type</button><button data-scope="instance">Cet élément</button>';panel.prepend(bar);let scope='global';for(const b of $$('button[data-scope]',bar))b.addEventListener('click',()=>{scope=b.dataset.scope;for(const x of $$('button[data-scope]',bar))x.classList.toggle('is-active',x===b);panel.dataset.reviewScope=scope;toast(`Portée ${scope}`);});panel.dataset.reviewScope=scope;return()=>scope;}
function readThemeSettings(panel){const ids=['background-mode','bg-one','bg-two','bg-transparent','bg-lightness','border-visible','border-width','border-radius','font-unified','font-body','font-heading','font-accent','font-weight','density'];const out={};for(const id of ids){const el=$(`#${id}`);if(!el)continue;out[id]=el.type==='checkbox'?el.checked:el.value;}return out;}
function applyThemeSettings(settings){for(const [id,value] of Object.entries(settings||{})){const el=$(`#${id}`);if(!el)continue;if(el.type==='checkbox')el.checked=Boolean(value);else el.value=String(value);el.dispatchEvent(new Event(el.type==='range'?'input':'change',{bubbles:true}));}toast('Preset appliqué ✓');}
function mountPresetBar(panel,namespace,canonical){const manager=new PresetManager({namespace,storage,canonical});const zone=document.createElement('div');zone.className='review-preset-zone';zone.innerHTML='<div class="review-toolbar"><strong>Profils :</strong><select data-preset-list></select><button data-preset-new>Nouveau</button><button data-preset-copy>Dupliquer</button><button data-preset-save>Enregistrer</button><button data-preset-validate>Valider</button><button data-preset-export>Exporter JSON</button></div><div data-preset-code></div>';panel.append(zone);const list=$('[data-preset-list]',zone),render=()=>{list.innerHTML=manager.list().map(p=>`<option value="${p.id}">${p.validated?'✓ ':''}${p.label}${p.canonical?' · défaut':''}</option>`).join('');if(manager.activeId)list.value=manager.activeId;};render();list.addEventListener('change',()=>{const p=manager.setActive(list.value);applyThemeSettings(p.settings);});$('[data-preset-new]',zone).addEventListener('click',()=>{const p=manager.create({label:`Profil ${manager.list().length+1}`,settings:readThemeSettings(panel)});render();list.value=p.id;toast('Profil créé');});$('[data-preset-copy]',zone).addEventListener('click',()=>{if(!list.value)return;try{const p=manager.duplicate(list.value);render();list.value=p.id;toast('Profil dupliqué');}catch{toast('Dupliquez d’abord un profil modifiable');}});$('[data-preset-save]',zone).addEventListener('click',()=>{let id=list.value,p=manager.get(id);if(!p||p.canonical){const created=manager.create({label:`Profil personnalisé ${Date.now()%1000}`,settings:readThemeSettings(panel)});id=created.id;}else manager.update(id,readThemeSettings(panel),{replace:true});manager.setActive(id);render();list.value=id;toast('Réglages enregistrés');});$('[data-preset-validate]',zone).addEventListener('click',()=>{const p=manager.get(list.value);if(!p||p.canonical)return toast('Le profil par défaut est déjà validé');manager.validate(p.id,true);render();toast('Profil validé ✓');});$('[data-preset-export]',zone).addEventListener('click',()=>{const host=$('[data-preset-code]',zone);new CodeBlock({value:manager.exportJSON(),language:'json',filename:`${namespace}.json`,theme:'dark',highlighted:true}).mount(host);toast('JSON prêt à copier ou télécharger');});}

function enhanceTheme(){const section=$('#theme-workshop');if(!section)return;const colorPanel=$('.demo-grid2 > .demo-panel',section),typePanel=$$('.demo-grid2 > .demo-panel',section)[1],density=$('#density')?.closest('.demo-panel');if(colorPanel){scopeControl(colorPanel,'theme-colors');const reset=document.createElement('button');reset.innerHTML='↺ Réglages initiaux';reset.addEventListener('click',()=>location.reload());$('.demo-controls',colorPanel)?.append(reset);const bg=$('#bg-lightness')?.closest('.demo-controls');if(bg&&!$('#review-gradient-balance')){const l=document.createElement('label');l.innerHTML='Balance dégradé <input id="review-gradient-balance" type="range" min="0" max="100" value="50"><output>50 %</output>';bg.append(l);const i=document.createElement('label');i.innerHTML='Intensité <input id="review-gradient-intensity" type="range" min="0" max="100" value="70"><output>70 %</output>';bg.append(i);for(const input of [$('#review-gradient-balance'),$('#review-gradient-intensity')])input.addEventListener('input',()=>{input.nextElementSibling.textContent=`${input.value} %`;const c1=$('#bg-one').value,c2=$('#bg-two').value,b=$('#review-gradient-balance').value,int=$('#review-gradient-intensity').value;document.documentElement.style.setProperty('--review-gradient',`linear-gradient(${$('#bg-direction').value},color-mix(in srgb,${c1} ${100-int}%,white),${b}%,color-mix(in srgb,${c2} ${100-int}%,white))`);document.body.style.backgroundImage='var(--review-gradient)';});}mountPresetBar(colorPanel,'theme-colors',[{id:'theme-colors.default',label:'Défaut',settings:readThemeSettings(colorPanel),canonical:true}]);}
 if(typePanel)mountPresetBar(typePanel,'typography',[{id:'typography.default',label:'Défaut',settings:readThemeSettings(typePanel),canonical:true}]);if(density)mountPresetBar(density,'density',[{id:'density.default',label:'Défaut',settings:readThemeSettings(density),canonical:true}]);
}

function enhanceResponsive(){const bar=$('.demo-responsive-toolbar');if(!bar)return;const auto=document.createElement('label');auto.innerHTML='<input id="review-breakpoint-auto" type="checkbox" checked> Breakpoint auto';bar.prepend(auto);const badge=document.createElement('span');badge.className='review-icon';bar.prepend(badge);const orient=$('#orientation');const syncIcon=()=>{const p=$('#device-profile').value;badge.innerHTML=p==='mobile'?svg.phone:p==='tablet'?svg.tablet:svg.desktop;orient.title=`Orientation ${orient.value}`;};$('#device-profile')?.addEventListener('change',syncIcon);orient?.addEventListener('change',()=>{syncIcon();toast(`${orient.value==='portrait'?'Portrait':'Paysage'} activé`);});syncIcon();const cb=$('#review-breakpoint-auto');const update=()=>{if(!cb.checked)return;const width=Math.round($('.demo-main')?.getBoundingClientRect().width||window.innerWidth);const values=[360,480,768,1024,1280];const nearest=values.reduce((a,b)=>Math.abs(b-width)<Math.abs(a-width)?b:a);$('#breakpoint').value=String(nearest);$('#breakpoint').dispatchEvent(new Event('change',{bubbles:true}));};cb.addEventListener('change',update);window.addEventListener('resize',()=>requestAnimationFrame(update));update();}

function enhanceSearch(){const select=$('#search-mode');if(!select)return;const segmented=document.createElement('div');segmented.className='review-segment';for(const opt of [...select.options]){const b=document.createElement('button');b.type='button';b.textContent=opt.textContent;b.dataset.mode=opt.value;b.classList.toggle('is-active',opt.value===select.value);b.addEventListener('click',()=>{select.value=opt.value;select.dispatchEvent(new Event('change',{bubbles:true}));for(const x of $$('button',segmented))x.classList.toggle('is-active',x===b);const examples={contains:'pommes',exact:'Dessert',regex:'^(Tarte|Soupe)',tokens:'pommes dessert',discrete:''};$('#search').value=examples[opt.value]||'';$('#search').dispatchEvent(new Event('input',{bubbles:true}));});segmented.append(b);}select.closest('label').append(segmented);select.hidden=true;const size=$('#card-size');if(size){const label=size.closest('label');label.firstChild.textContent='Taille rendu ';label.title='Ajuste les cartes, cartes compactes, galerie et pellicule lorsque le renderer le permet.';}}

function enhanceTable(){const input=$('#table-search');if(!input)return;const clear=document.createElement('button');clear.type='button';clear.title='Réinitialiser la recherche du tableau';clear.innerHTML=svg.close;clear.className='review-icon';input.insertAdjacentElement('afterend',clear);clear.addEventListener('click',()=>{input.value='';input.dispatchEvent(new Event('input',{bubbles:true}));toast('Recherche tableau réinitialisée');});const exportBtn=$('#table-export');exportBtn?.addEventListener('click',()=>setTimeout(()=>{const table=$('#table table');if(!table)return;const csv=$$('tr',table).map(row=>$$('th,td',row).map(c=>`"${c.innerText.replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='table-wiz.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),0);toast('CSV téléchargé ✓');},0));}

async function enhanceJson(){const host=$('#json-studio');if(!host)return;const data=await fetch('data/mixed.json').then(r=>r.json());const rawBtn=$('[data-json-view="raw"]',host);rawBtn?.addEventListener('click',()=>setTimeout(()=>{const editor=$('#json-editor');new CodeBlock({value:JSON.stringify(data,null,2),language:'json',filename:'dataset.json',theme:'light',highlighted:true,editable:true}).mount(editor);},0));const diff=$('#json-diff-output');if(diff){const note=document.createElement('div');note.className='review-toolbar';note.innerHTML='<strong>Légende Diff :</strong><span class="review-added">Ajouté</span><span class="review-removed">Supprimé</span><span class="review-changed">Modifié</span><label>Point de vue <select id="review-diff-source"><option value="reference">Référence → Modifié</option><option value="modified">Modifié → Référence</option></select></label>';diff.before(note);}}

function enhanceDataWiz(){const stats=$('#stats');if(!stats)return;const explain=document.createElement('div');explain.className='review-data-grid';explain.innerHTML='<div class="review-data-card"><strong>Statistiques numériques</strong><span>minimum, maximum, moyenne et distribution sur les champs numériques.</span></div><div class="review-data-card"><strong>Regroupement</strong><span>nombre d’éléments par catégorie, dérivé du même dataset.</span></div>';stats.parentElement.before(explain);}

function enhancePanel(){const panel=$('#panel');if(!panel)return;const collapse=$('#panel-collapse');collapse?.addEventListener('click',()=>setTimeout(()=>{panel.dataset.reviewCompact=String(!panel.querySelector('.nlab-floating-panel__body')?.offsetHeight);},0));const actions=$('.panel-actions',panel);if(actions){const more=document.createElement('button');more.type='button';more.title='Plus d’actions';more.textContent='•••';more.addEventListener('click',()=>toast('Les actions secondaires seront déplacées ici lorsque le panneau devient étroit.'));actions.insertBefore(more,$('#panel-close'));}const close=$('#panel-close');if(close){close.innerHTML=svg.close;close.title='Fermer InspectorPanel';}}

function enhanceQr(){const type=$('#qr-content-type');if(type){for(const opt of [...type.options])opt.disabled=false;const placeholder=()=>{const map={url:'https://exemple.fr/page',text:'Texte libre à encoder',contact:'Nom, téléphone, email'};$('#qr-url').placeholder=map[type.value]||'';};type.addEventListener('change',()=>{placeholder();toast(`Type QR : ${type.options[type.selectedIndex].text}`);});placeholder();}const logo=$('#qr-logo-enabled')?.closest('label'),style=$('#qr-logo-style')?.closest('label');if(logo&&style)logo.parentElement.insertBefore(style,logo.nextSibling);const reset=document.createElement('button');reset.type='button';reset.innerHTML='↺ Réglages QR par défaut';reset.addEventListener('click',()=>{for(const [id,val] of Object.entries({'qr-width':'220','qr-ecc':'M','qr-dark':'#111827','qr-light':'#ffffff','qr-logo-style':'color'})){const el=$(`#${id}`);if(el){el.value=val;el.dispatchEvent(new Event('change',{bubbles:true}));}}$('#qr-transparent').checked=false;$('#qr-logo-enabled').checked=false;$('#qr-refresh').click();toast('QR réinitialisé');});$('.qr-controls')?.append(reset);}

function enhanceCodeBlock(){const section=$('#code-block');if(!section)return;const zoom=document.createElement('label');zoom.className='review-slider';zoom.innerHTML='<span>Taille texte</span><input id="review-code-zoom" type="range" min="70" max="160" value="100"><output>100 %</output>';section.querySelector('.demo-code-tabs')?.after(zoom);$('#review-code-zoom')?.addEventListener('input',e=>{e.target.nextElementSibling.textContent=`${e.target.value} %`;section.style.setProperty('--review-code-size',`${e.target.value/100}em`);const styleId='review-code-font-style';let s=$(`#${styleId}`);if(!s){s=document.createElement('style');s.id=styleId;document.head.append(s);}s.textContent='#code-block .nlab-codeblock__pre,#code-block .nlab-codeblock__editor{font-size:var(--review-code-size)!important}';});}

async function init(){style();decorateSubsections();enhanceNav();enhanceTheme();enhanceResponsive();enhanceSearch();enhanceTable();await enhanceJson();enhanceDataWiz();enhancePanel();enhanceQr();enhanceCodeBlock();}
setTimeout(()=>init().catch(err=>{console.error('review-pass',err);toast(`Review pass: ${err.message}`);}),0);
