export class NavigationWiz {
  constructor({ root=document,contentSelector='main',headingSelector='h1,h2,h3',activeClass='is-active' }={}) { this.root=root;this.contentSelector=contentSelector;this.headingSelector=headingSelector;this.activeClass=activeClass;this.items=[];this.container=null; }
  buildTree(){const content=this.root.querySelector(this.contentSelector);if(!content)return[];const headings=[...content.querySelectorAll(this.headingSelector)],stack=[],roots=[];this.items=headings.map((heading,index)=>{if(!heading.id)heading.id=`section-${index+1}`;return{id:heading.id,title:heading.childNodes[0]?.textContent?.trim()||heading.textContent.trim(),level:Number(heading.tagName.slice(1)),element:heading,children:[]};});for(const item of this.items){while(stack.length&&stack.at(-1).level>=item.level)stack.pop();(stack.length?stack.at(-1).children:roots).push(item);stack.push(item);}return roots;}
  render(container,tree=this.buildTree()){if(!container)return this;this.container=container;const make=(nodes)=>{const list=document.createElement('ul');for(const node of nodes){const li=document.createElement('li');li.dataset.navLevel=String(node.level);const link=document.createElement('a');link.href=`#${encodeURIComponent(node.id)}`;link.textContent=node.title;link.dataset.navTarget=node.id;if(node.children.length){const details=document.createElement('details');details.open=node.level<=2;details.dataset.navNode=node.id;const summary=document.createElement('summary');summary.append(link);details.append(summary,make(node.children));li.append(details);}else li.append(link);list.append(li);}return list;};container.replaceChildren(make(tree));return this;}
  expandAll(){for(const item of this.container?.querySelectorAll('details')??[])item.open=true;return this;}
  collapseAll(){for(const item of this.container?.querySelectorAll('details')??[])item.open=false;return this;}
  setDepth(depth=2){const max=Math.max(1,Math.min(6,Number(depth)||1));for(const item of this.container?.querySelectorAll('details')??[])item.open=Number(item.closest('li')?.dataset.navLevel||9)<=max;return this;}
  defaultState(){return this.setDepth(2);}
  observe(container,{rootMargin='-20% 0px -70% 0px'}={}){if(!globalThis.IntersectionObserver)return this;const links=new Map([...container.querySelectorAll('[data-nav-target]')].map((link)=>[link.dataset.navTarget,link]));this.observer=new IntersectionObserver((entries)=>{const visible=entries.filter((entry)=>entry.isIntersecting).sort((a,b)=>a.boundingClientRect.top-b.boundingClientRect.top)[0];if(!visible)return;for(const link of links.values())link.classList.remove(this.activeClass);links.get(visible.target.id)?.classList.add(this.activeClass);},{rootMargin});for(const item of this.items)this.observer.observe(item.element);return this;}
  restore(hash=globalThis.location?.hash??''){if(!hash)return false;const id=decodeURIComponent(hash.slice(1)),target=this.root.getElementById?.(id);target?.scrollIntoView?.({block:'start'});return Boolean(target);}
  destroy(){this.observer?.disconnect();}
}
