import assert from 'node:assert/strict';
import {DiagnosticIdRegistry,DiagnosticIdError} from '../core/diagnostic-id-registry.js';
const r=new DiagnosticIdRegistry();
r.register({humanId:'DMO-042',technicalId:'demo.theme.background.gradient',kind:'section',title:'Gradient',test:{objective:'Check gradient',thingsToTest:['Stops','Angle'],expectedResult:'Gradient visible'},files:['demo.css'],providers:['theme'],dependencies:['theme.engine'],configuration:{scope:'global'},metadata:{owner:'A'}});
assert.equal(r.get('DMO-042').technicalId,'demo.theme.background.gradient');
assert.equal(r.get('demo.theme.background.gradient').humanId,'DMO-042');
assert.equal(r.nextHumanId(),'DMO-043');
assert.deepEqual(r.attributes('DMO-042'),{'data-test-id':'DMO-042','data-technical-id':'demo.theme.background.gradient','data-test-kind':'section'});
const classic=r.describe('DMO-042');assert.equal(classic.files,undefined);assert.equal(classic.objective,'Check gradient');
const advanced=r.describe('DMO-042',{mode:'advanced'});assert.deepEqual(advanced.files,['demo.css']);assert.deepEqual(advanced.configuration,{scope:'global'});
const got=r.get('DMO-042');got.configuration.scope='mutated';assert.equal(r.get('DMO-042').configuration.scope,'global');
assert.throws(()=>r.register({humanId:'bad',technicalId:'demo.valid'}),e=>e instanceof DiagnosticIdError&&e.code==='INVALID_HUMAN_ID');
assert.throws(()=>r.register({humanId:'DMO-043',technicalId:'Bad Tech'}),e=>e.code==='INVALID_TECHNICAL_ID');
assert.throws(()=>r.register({humanId:'DMO-042',technicalId:'demo.other'}),e=>e.code==='DUPLICATE_ID');
r.register({humanId:'DMO-042',technicalId:'demo.theme.background.gradient.v2',kind:'section',title:'New'},{replace:true});assert.equal(r.get('demo.theme.background.gradient'),null);assert.equal(r.get('DMO-042').title,'New');
r.register({humanId:'SEC-100',technicalId:'demo.section.one',kind:'section'});r.register({humanId:'CMP-010',technicalId:'demo.component.a',kind:'component'});assert.deepEqual(r.list({kind:'section'}).map(e=>e.humanId),['DMO-042','SEC-100']);assert.deepEqual(r.list({technicalPrefix:'demo.section'}).map(e=>e.humanId),['SEC-100']);
const seq=new DiagnosticIdRegistry();assert.equal(seq.nextHumanId(),'DMO-001');seq.register({humanId:'DMO-001',technicalId:'demo.one'});seq.register({humanId:'DMO-009',technicalId:'demo.nine'});assert.equal(seq.nextHumanId(),'DMO-010');
const conflicts=new DiagnosticIdRegistry({entries:[{humanId:'DMO-100',technicalId:'demo.a'},{humanId:'DMO-101',technicalId:'demo.b'}]});assert.throws(()=>conflicts.register({humanId:'DMO-100',technicalId:'demo.b'},{replace:true}),e=>e.code==='AMBIGUOUS_REPLACE');assert.equal(conflicts.get('DMO-100').technicalId,'demo.a');assert.equal(conflicts.get('demo.b').humanId,'DMO-101');
assert.deepEqual(r.resolveMany(['DMO-042','missing','demo.section.one']).map(e=>e.humanId),['DMO-042','SEC-100']);assert.equal(r.snapshot().length,3);r.unregister('CMP-010');assert.equal(r.has('CMP-010'),false);assert.throws(()=>r.attributes('missing'),e=>e.code==='UNKNOWN_ID');
console.log('diagnostic id registry tests: ok');
