import assert from 'node:assert/strict';
import { JsonStudio, JsonStudioError } from '../wiz/json-studio.js';

const source={title:'Demo',nested:{value:1},rows:[{id:'A',score:1},{id:'B',score:2}]};
const studio=new JsonStudio({data:source,table:{}});
assert.deepEqual(studio.get(),source);const copy=studio.get();copy.nested.value=999;assert.equal(studio.get('nested.value'),1);
studio.set('nested.value',2);assert.equal(studio.get('nested.value'),2);assert.equal(studio.historyState().canUndo,true);studio.undo();assert.equal(studio.get('nested.value'),1);studio.redo();assert.equal(studio.get('nested.value'),2);
studio.add('rows',{id:'C',score:3});assert.equal(studio.get('rows').length,3);studio.move('rows',2,0);assert.deepEqual(studio.get('rows').map(r=>r.id),['C','A','B']);studio.remove('rows',1);assert.deepEqual(studio.get('rows').map(r=>r.id),['C','B']);assert.throws(()=>studio.remove('rows',99),e=>e instanceof JsonStudioError&&e.code==='INVALID_ARRAY_INDEX');assert.throws(()=>studio.add('nested',1),e=>e.code==='NOT_AN_ARRAY');
const beforeInvalid=studio.get();studio.importRaw('{bad');assert.equal(studio.lastError.code,'INVALID_JSON');assert.deepEqual(studio.get(),beforeInvalid);studio.importRaw('{"ok":true}');assert.deepEqual(studio.get(),{ok:true});studio.undo();assert.deepEqual(studio.get(),beforeInvalid);
const unsafe=new JsonStudio({data:{safe:true},table:{}});assert.throws(()=>unsafe.set('__proto__.polluted','yes'),e=>e.code==='UNSAFE_PATH');assert.equal({}.polluted,undefined);
const atomic=new JsonStudio({data:{a:1,b:2},table:{}});atomic.transaction(d=>{d.a=3;d.b=4},{label:'batch'});assert.deepEqual(atomic.get(),{a:3,b:4});assert.equal(atomic.historyState().nextUndo,'batch');atomic.undo();assert.deepEqual(atomic.get(),{a:1,b:2});
const limit=new JsonStudio({data:{n:0},table:{},historyLimit:2});limit.set('n',1).set('n',2).set('n',3);assert.equal(limit.historyState().undoCount,2);limit.undo().undo();assert.equal(limit.get('n'),1);assert.equal(limit.historyState().canUndo,false);limit.set('n',9);assert.equal(limit.historyState().canRedo,false);
const diffStudio=new JsonStudio({data:{a:1,b:[1,2]},table:{}});diffStudio.set('a',2).add('b',3);const diff=diffStudio.diff();assert.ok(diff.some(c=>c.type==='changed'&&c.path==='a'));assert.ok(diff.some(c=>c.type==='added'&&c.path==='b.2'));diffStudio.markOriginal();assert.deepEqual(diffStudio.diff(),[]);diffStudio.set('a',5).resetToOriginal();assert.equal(diffStudio.get('a'),2);
const root=new JsonStudio({data:{x:1},table:{}});root.set('',{x:2});assert.deepEqual(root.get(),{x:2});root.undo();assert.deepEqual(root.get(),{x:1});root.unset('x');assert.deepEqual(root.get(),{});
console.log('json studio core tests: ok');
class FakeElement{constructor(tagName='div',ownerDocument=null){this.tagName=tagName.toUpperCase();this.ownerDocument=ownerDocument;this.children=[];this.parentElement=null;this.attributes=new Map();this.listeners=new Map();this.style={};this.className='';this.textContent='';this.value='';this.type='';this.rows=0;this.open=false;this.clientWidth=800}append(...nodes){for(const node of nodes){if(node&&typeof node==='object')node.parentElement=this;this.children.push(node)}}replaceChildren(...nodes){this.children=[];this.append(...nodes)}setAttribute(name,value){this.attributes.set(name,String(value))}removeAttribute(name){this.attributes.delete(name)}addEventListener(type,listener){if(!this.listeners.has(type))this.listeners.set(type,new Set());this.listeners.get(type).add(listener)}removeEventListener(type,listener){this.listeners.get(type)?.delete(listener)}dispatch(type,event={}){for(const listener of [...(this.listeners.get(type)??[])])listener(event)}}
class FakeDocument{createElement(tag){return new FakeElement(tag,this)}}
function findAttr(node,name,value){if(node?.attributes?.get(name)===value)return node;for(const child of node?.children??[]){const found=findAttr(child,name,value);if(found)return found}return null}
function findTagWithText(node,tag,text){if(node?.tagName===tag&&node.textContent===text)return node;for(const child of node?.children??[]){const found=findTagWithText(child,tag,text);if(found)return found}return null}
const doc=new FakeDocument();const treeContainer=new FakeElement('div',doc);const domStudio=new JsonStudio({data:{'<img onerror=alert(1)>':'<script>alert(1)</script>',count:3},table:{render(){}}});domStudio.render(treeContainer,{view:'tree',document:doc});assert.ok(findTagWithText(treeContainer,'STRONG','<img onerror=alert(1)>'));assert.ok(findTagWithText(treeContainer,'CODE','"<script>alert(1)</script>"'));const openButton=findTagWithText(treeContainer,'BUTTON','Tout déplier');openButton.dispatch('click');assert.equal(treeContainer.children[1].children[0].open,true);
const formContainer=new FakeElement('div',doc);domStudio.render(formContainer,{view:'form',document:doc});const numberInput=findAttr(formContainer,'data-json-input','count');assert.ok(numberInput);numberInput.value='9';numberInput.dispatch('change');assert.equal(domStudio.get('count'),9);numberInput.value='bad';numberInput.dispatch('change');assert.equal(domStudio.get('count'),9);assert.equal(numberInput.attributes.get('aria-invalid'),'true');
const rawContainer=new FakeElement('div',doc);const rawStudio=new JsonStudio({data:{ok:true},table:{}});rawStudio.render(rawContainer,{view:'raw',document:doc});const textarea=rawContainer.children[0];textarea.value='{bad';textarea.dispatch('change');assert.deepEqual(rawStudio.get(),{ok:true});assert.equal(textarea.attributes.get('aria-invalid'),'true');textarea.value='{"ok":false}';textarea.dispatch('change');assert.deepEqual(rawStudio.get(),{ok:false});assert.equal(textarea.attributes.has('aria-invalid'),false);
let tableCalls=0;const tableContainer=new FakeElement('div',doc);new JsonStudio({data:[{id:1}],table:{render(container,rows){tableCalls++;assert.equal(container,tableContainer);assert.equal(rows.length,1)}}}).render(tableContainer,{view:'table',document:doc});assert.equal(tableCalls,1);
const replacement = new JsonStudio({data:{n:0},table:{}});replacement.set('n',1);assert.equal(replacement.historyState().canUndo,true);replacement.setData({n:9});assert.equal(replacement.historyState().canUndo,false);assert.equal(replacement.historyState().canRedo,false);assert.equal(replacement.get('n'),9);
const dottedContainer=new FakeElement('div',doc);const dottedStudio=new JsonStudio({data:{'a.b':1},table:{}});dottedStudio.render(dottedContainer,{view:'form',document:doc});const dottedInput=findAttr(dottedContainer,'data-json-input','a.b');assert.ok(dottedInput);dottedInput.value='4';dottedInput.dispatch('change');assert.equal(dottedStudio.get(['a.b']),4);assert.equal(dottedStudio.get('a.b'),undefined);
console.log('json studio DOM tests: ok');
