import assert from 'node:assert/strict';
import {SessionConfigRegistry,SessionConfigError} from '../core/session-config-registry.js';
let now=1000;const events=[];const registry=new SessionConfigRegistry({clock:()=>++now,onChange:event=>events.push(event.type)});
const first=registry.publish('theme.main',{scheme:'dark',tokens:{accent:'#08f'}},{metadata:{studio:'theme'}});
assert.equal(first.revision,1);assert.equal(first.reference,true);
first.config.scheme='light';assert.equal(registry.get('theme.main').config.scheme,'dark');
const same=registry.publish('theme.main',{tokens:{accent:'#08f'},scheme:'dark'});assert.equal(same.revision,1);
const changed=registry.publish('theme.main',{scheme:'light'});assert.equal(changed.revision,2);
registry.publish('qr.main',{size:256},{reference:false});
assert.deepEqual(registry.list().map(entry=>entry.key),['qr.main','theme.main']);
assert.deepEqual(Object.keys(registry.payload({referencesOnly:true}).modules),['theme.main']);
const text=registry.exportText();assert.match(text,/nlab\.session-config/);
const imported=new SessionConfigRegistry({clock:()=>++now});imported.importText(text);assert.equal(imported.get('theme.main').config.scheme,'light');assert.equal(imported.get('qr.main').reference,false);
imported.setReference('qr.main',true);assert.equal(imported.get('qr.main').reference,true);
assert.equal(imported.remove('missing'),false);assert.equal(imported.remove('qr.main'),true);
assert.throws(()=>registry.publish('Bad Key',{}),error=>error instanceof SessionConfigError&&error.code==='INVALID_KEY');
assert.throws(()=>registry.publish('bad.number',{value:Infinity}),error=>error.code==='INVALID_NUMBER');
const cyclic={};cyclic.self=cyclic;assert.throws(()=>registry.publish('bad.cycle',cyclic),error=>error.code==='CYCLIC_CONFIG');
const unsafe=Object.create(null);unsafe.safe=1;assert.throws(()=>registry.publish('bad.proto',unsafe),error=>error.code==='INVALID_CONFIG');
assert.throws(()=>registry.importText('{oops'),error=>error.code==='INVALID_JSON');
const unsubscribe=registry.subscribe(()=>events.push('sub'));registry.setReference('theme.main',false);unsubscribe();registry.setReference('theme.main',true);assert.equal(events.filter(x=>x==='sub').length,1);
console.log('session config registry tests: ok');
