(()=>{'use strict';
const S={data:null,refs:null,cfg:null,items:[],selected:0,view:'form',dirty:false,previewUrls:new Map()};
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
async function load(){const [data,refs,cfg,semanticTheme]=await Promise.all(['demo-catalog.json','demo-references.json','demo-config.json','../../themes/data-editor-semantic-theme.json'].map(x=>fetch(x).then(r=>{if(!r.ok)throw new Error(`${x}: HTTP ${r.status}`);return r.json()})));S.data=data;S.refs=refs;S.cfg=cfg.Data;S.items=data.Data[S.cfg.collection];applyTheme(semanticTheme.Data?.tokens||{});bind();renderAll();}
function applyTheme(base){for(const[k,v]of Object.entries({...base,...(S.cfg.editor_theme_overrides||{})}))document.documentElement.style.setProperty(`--${k}`,v)}
function dict(k){return S.data?.dictionnaire_donnees?.champs?.[k]||{};}function conf(k){return S.cfg.fields?.[k]||{};}
function refDef(path){return S.cfg.references?.[path]||S.cfg.references?.[path.replace(/\.\d+\./g,'.')]||null;}
function source(name){if(name==='items')return S.items;return S.refs?.Data?.[name]||[];}
function resolve(path,id){const d=refDef(path);if(!d)return null;return source(d.source).find(x=>String(x[d.id_field])===String(id))||null;}
function displayRef(path,id,forcedMode){const hit=resolve(path,id),mode=forcedMode||$('#idMode')?.value||S.cfg.id_display.default;if(!hit)return String(id??'');const d=refDef(path),label=hit[d.label_field];if(mode==='id')return id;if(mode==='label')return label;return `${id} — ${label}`;}
function semantic(path,id){const d=refDef(path),hit=resolve(path,id);return d?.semantic_field&&hit?hit[d.semantic_field]:'neutral';}
function bind(){
 $('#search').oninput=renderList;$('#idMode').value=S.cfg.id_display.default;$('#idMode').onchange=renderAll;$('#searchMode').value=S.cfg.search.default;$('#searchMode').onchange=renderList;
 document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{S.view=b.dataset.view;renderWorkspace();});
 $('#exportAll').onclick=()=>download(S.data,'demo-catalog-export.json');$('#exportRefs').onclick=()=>download(S.refs,'demo-references-export.json');$('#exportOne').onclick=()=>download(S.items[S.selected],`${S.items[S.selected]?.id||'record'}.json`);
 $('#importAll').onclick=()=>$('#fileAll').click();$('#fileAll').onchange=e=>readJsonFile(e.target.files[0],o=>{if(!o?.Data?.[S.cfg.collection])throw new Error(`Collection ${S.cfg.collection} absente`);S.data=o;S.items=o.Data[S.cfg.collection];S.selected=0;markDirty();renderAll();});
 $('#importRefs').onclick=()=>$('#fileRefs').click();$('#fileRefs').onchange=e=>readJsonFile(e.target.files[0],o=>{if(!o?.Data)throw new Error('Data absent du référentiel');S.refs=o;markDirty();renderAll();});
 $('#importOne').onclick=()=>$('#fileOne').click();$('#fileOne').onchange=e=>readJsonFile(e.target.files[0],o=>importRecord(o.Data?.item||o));
 $('#addRecord').onclick=()=>{const base={id:nextId(),name:'Nouvelle fiche',short_text:'',long_text:'',category_id:'CAT_ROOT',status_id:'STA_DRAFT',priority:S.items.length+1,price:{value:0,currency:'EUR'},active:true,tags:[],links:[],media:[],metrics:{score:0,views:0,duration_min:0},related_ids:[]};S.items.push(base);S.selected=S.items.length-1;markDirty();renderAll();};
 $('#deleteRecord').onclick=()=>{if(!S.items.length)return;S.items.splice(S.selected,1);S.selected=Math.max(0,S.selected-1);markDirty();renderAll();};
}
function nextId(){let n=1,id;do{id=`ITM${String(n++).padStart(3,'0')}`}while(S.items.some(x=>x.id===id));return id;}
function importRecord(record){if(!record||typeof record!=='object')throw new Error('Fiche JSON invalide');const incoming=structuredClone(record),idx=S.items.findIndex(x=>x.id===incoming.id);if(idx>=0){const policy=S.cfg.import_record?.on_duplicate||'duplicate_new_id';if(policy==='replace')S.items[idx]=incoming;else if(policy==='reject')throw new Error(`ID déjà présent : ${incoming.id}`);else{incoming.id=nextId();S.items.push(incoming);S.selected=S.items.length-1;}}else{S.items.push(incoming);S.selected=S.items.length-1;}markDirty();renderAll();}
function readJsonFile(file,cb){if(!file)return;const r=new FileReader();r.onload=()=>{try{cb(JSON.parse(r.result))}catch(e){alert('Import impossible : '+e.message)}};r.readAsText(file);}
function download(o,name){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(o,null,2)],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),700)}
function markDirty(){S.dirty=true;$('#dirty').textContent='● Modifié';$('#dirty').className='semantic-temporary'}
function resolvedSearchText(x){const parts=[x.id,x.name];for(const[path,d]of Object.entries(S.cfg.references||{})){if(path.includes('.'))continue;const v=x[path];if(Array.isArray(v))for(const id of v)parts.push(displayRef(path,id,'id_label'));else if(v!=null)parts.push(displayRef(path,v,'id_label'));}return parts.join(' ')}
function searchText(x){const mode=$('#searchMode').value,q=norm($('#search').value);if(!q)return true;let hay='';if(mode==='id')hay=x.id;else if(mode==='label')hay=x.name;else if(mode==='id_label')hay=`${x.id} ${x.name} ${resolvedSearchText(x)}`;else hay=`${JSON.stringify(x)} ${resolvedSearchText(x)}`;return norm(hay).includes(q)}
function renderList(){const box=$('#records');box.innerHTML=S.items.map((x,i)=>({x,i})).filter(({x})=>searchText(x)).map(({x,i})=>`<button class="record ${i===S.selected?'active':''}" data-i="${i}"><span class="status-dot" data-semantic="${semantic('status_id',x.status_id)}"></span><strong>${esc(displayRef('related_ids',x.id))}</strong><br><small>${esc(displayRef('status_id',x.status_id))}</small></button>`).join('');box.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>{S.selected=+b.dataset.i;renderAll()})}
function renderAll(){renderList();renderWorkspace();$('#count').textContent=`${S.items.length} fiches`;}
function renderWorkspace(){document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===S.view));if(S.view==='form')renderForm();else if(S.view==='structured')renderStructured();else if(S.view==='table')renderTable();else if(S.view==='tree')renderTree();else renderRaw();}
function renderForm(){const x=S.items[S.selected]||{};$('#workspace').innerHTML=`<div class="grid">${Object.entries(x).map(([k,v])=>renderField(k,v,k)).join('')}</div>`;bindInputs($('#workspace'));}
function renderField(k,v,path){const h=dict(k),c=conf(k),full=['long_text','links','media','metrics','tags','related_ids'].includes(k);let body='';if(c.renderer==='reference')body=renderReference(path,v);else if(c.renderer==='reference_array')body=renderRefArray(path,v);else if(c.renderer==='links')body=renderLinks(path,v);else if(c.renderer==='media')body=renderMedia(path,v);else if(c.renderer==='metrics')body=renderMetrics(path,v);else if(Array.isArray(v))body=renderArray(path,v);else if(v&&typeof v==='object')body=`<div class="nested">${Object.entries(v).map(([sk,sv])=>renderScalar(`${path}.${sk}`,sv,sk)).join('')}</div>`;else body=renderScalar(path,v,k,c);return `<section class="field ${full?'full':''}"><div class="field-head"><label>${esc(h.libelle||k)}</label><code>${esc(k)}</code></div><div class="help">${esc(h.description||'')}</div>${body}</section>`}
function renderScalar(path,v,k,c={}){if(c.renderer==='textarea'||typeof v==='string'&&String(v).length>90)return `<textarea data-path="${esc(path)}" rows="5">${esc(v)}</textarea>`;if(typeof v==='boolean')return `<input type="checkbox" data-path="${esc(path)}" ${v?'checked':''}>`;if(typeof v==='number')return `<input type="number" step="any" data-path="${esc(path)}" value="${esc(v)}">`;return `<input data-path="${esc(path)}" value="${esc(v)}" ${c.editable===false?'readonly':''}>`}
function optionLabel(path,o){const d=refDef(path),mode=$('#idMode')?.value||S.cfg.id_display.default,id=o[d.id_field],label=o[d.label_field];return mode==='id'?id:mode==='label'?label:`${id} — ${label}`;}
function renderReference(path,v){const d=refDef(path),arr=source(d.source),profile=conf(path.split('.').at(-1))?.input_profile||'fixed_single';return `<select data-path="${esc(path)}">${arr.map(o=>`<option value="${esc(o[d.id_field])}" ${String(o[d.id_field])===String(v)?'selected':''}>${esc(optionLabel(path,o))}</option>`).join('')}</select><span class="resolved-label semantic-${semantic(path,v)}">${esc(displayRef(path,v))}</span><small>${esc(profile)}</small>`}
function renderArray(path,a){return `<div>${a.map((v,i)=>`<div class="array-row"><input data-path="${path}.${i}" value="${esc(v)}"><div class="array-actions"><button data-move="${path}" data-i="${i}" data-d="-1">↑</button><button data-move="${path}" data-i="${i}" data-d="1">↓</button><button data-remove="${path}" data-i="${i}">×</button></div></div>`).join('')}<button class="btn" data-add="${path}">＋ Ajouter</button></div>`}
function renderRefArray(path,a){const d=refDef(path),arr=source(d.source);return `<div>${a.map((v,i)=>`<div class="array-row"><select data-path="${path}.${i}">${arr.map(o=>`<option value="${esc(o[d.id_field])}" ${String(o[d.id_field])===String(v)?'selected':''}>${esc(optionLabel(path,o))}</option>`).join('')}</select><div class="array-actions"><button data-move="${path}" data-i="${i}" data-d="-1">↑</button><button data-move="${path}" data-i="${i}" data-d="1">↓</button><button data-remove="${path}" data-i="${i}">×</button></div></div>`).join('')}<button class="btn" data-add-ref="${path}">＋ Ajouter une référence</button></div>`}
function renderLinks(path,a){return `<div>${a.map((o,i)=>`<div class="link-card"><a href="${esc(o.url)}" target="${o.target==='new_tab'?'_blank':'_self'}">${esc(o.label||o.url)}</a><div class="array-row"><div>${Object.entries(o).map(([k,v])=>renderScalar(`${path}.${i}.${k}`,v,k)).join('')}</div><div class="array-actions"><button data-move="${path}" data-i="${i}" data-d="-1">↑</button><button data-move="${path}" data-i="${i}" data-d="1">↓</button><button data-remove="${path}" data-i="${i}">×</button></div></div></div>`).join('')}<button class="btn" data-add-object="${path}" data-kind="link">＋ Ajouter un lien</button></div>`}
function previewFor(path,o){return S.previewUrls.get(path)||o.url||'';}
function renderMedia(path,a){return `<div>${a.map((o,i)=>{const p=`${path}.${i}`,src=previewFor(p,o);return `<div class="link-card">${o.type_id==='MED_IMAGE'&&src?`<img class="media-preview" src="${esc(src)}" alt="${esc(o.alt)}">`:''}<strong>${esc(displayRef('media.type_id',o.type_id))}</strong><div>${Object.entries(o).map(([k,v])=>renderScalar(`${p}.${k}`,v,k)).join('')}</div><div class="image-tools"><button class="btn" data-pick-image="${p}">Modifier l'image</button><button class="btn" data-move="${path}" data-i="${i}" data-d="-1">↑</button><button class="btn" data-move="${path}" data-i="${i}" data-d="1">↓</button><button class="btn" data-remove="${path}" data-i="${i}">×</button><input class="hidden" type="file" accept="image/*" data-image-input="${p}"></div></div>`}).join('')}<button class="btn" data-add-object="${path}" data-kind="media">＋ Ajouter un média</button></div>`}
function renderMetrics(path,o){return `<div>${Object.entries(o).map(([k,v])=>{const sem=k==='score'?(v<40?'invalid':v<70?'warning':'resolved'):'neutral';return `<span class="metric semantic-${sem}"><small>${esc(k)}</small><strong>${esc(v)}</strong></span>`}).join('')}</div><div class="nested">${Object.entries(o).map(([k,v])=>renderScalar(`${path}.${k}`,v,k)).join('')}</div>`}
function bindInputs(root){root.querySelectorAll('[data-path]').forEach(el=>el.onchange=()=>{setPath(S.items[S.selected],el.dataset.path,el.type==='checkbox'?el.checked:el.type==='number'?Number(el.value):el.value);markDirty();renderList();});root.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{getPath(S.items[S.selected],b.dataset.remove).splice(+b.dataset.i,1);markDirty();renderForm()});root.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>move(getPath(S.items[S.selected],b.dataset.move),+b.dataset.i,+b.dataset.d,renderForm));root.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{getPath(S.items[S.selected],b.dataset.add).push('');markDirty();renderForm()});root.querySelectorAll('[data-add-ref]').forEach(b=>b.onclick=()=>{const d=refDef(b.dataset.addRef),arr=source(d.source);getPath(S.items[S.selected],b.dataset.addRef).push(arr[0]?.[d.id_field]||'');markDirty();renderForm()});root.querySelectorAll('[data-add-object]').forEach(b=>b.onclick=()=>{getPath(S.items[S.selected],b.dataset.addObject).push(b.dataset.kind==='link'?{label:'Nouveau lien',url:'https://example.com',target:'new_tab',icon:'external_link'}:{id:'MEDIA_NEW',type_id:'MED_IMAGE',filename:'image.svg',url:'./assets/images/image.svg',alt:'Nouveau média'});markDirty();renderForm()});root.querySelectorAll('[data-pick-image]').forEach(b=>b.onclick=()=>root.querySelector(`[data-image-input="${CSS.escape(b.dataset.pickImage)}"]`)?.click());root.querySelectorAll('[data-image-input]').forEach(inp=>inp.onchange=()=>{const f=inp.files[0];if(!f)return;const o=getPath(S.items[S.selected],inp.dataset.imageInput),old=S.previewUrls.get(inp.dataset.imageInput);if(old)URL.revokeObjectURL(old);S.previewUrls.set(inp.dataset.imageInput,URL.createObjectURL(f));o.filename=f.name;o.url=(S.cfg.media_upload?.path_prefix||'./assets/images/')+f.name;markDirty();renderForm();});}
function move(a,i,d,rerender=renderAll){const j=i+d;if(!Array.isArray(a)||j<0||j>=a.length)return;[a[i],a[j]]=[a[j],a[i]];markDirty();rerender()}
function getPath(o,p){return p.split('.').reduce((v,k)=>v?.[k],o)}function setPath(o,p,val){const parts=p.split('.');let cur=o;for(let i=0;i<parts.length-1;i++)cur=cur[parts[i]];cur[parts.at(-1)]=val;}
function structuredNode(value,key='root'){if(Array.isArray(value))return `<details open><summary>${esc(key)} [${value.length}]</summary>${value.map((v,i)=>structuredNode(v,String(i))).join('')}</details>`;if(value&&typeof value==='object')return `<details open><summary>${esc(key)} {${Object.keys(value).length}}</summary>${Object.entries(value).map(([k,v])=>structuredNode(v,k)).join('')}</details>`;return `<div class="structured-leaf"><code>${esc(key)}</code> <span>${esc(value)}</span></div>`}
function renderStructured(){const x=S.items[S.selected]||{};$('#workspace').innerHTML=`<div class="structured-tree">${structuredNode(x,'fiche')}</div>`}
function renderTable(){const cols=['id','name','category_id','status_id','priority','active'];$('#workspace').innerHTML=`<div style="overflow:auto"><table><thead><tr>${cols.map(c=>`<th>${esc(dict(c).libelle||c)}</th>`).join('')}</tr></thead><tbody>${S.items.map(x=>`<tr>${cols.map(c=>`<td>${c.endsWith('_id')?esc(displayRef(c,x[c])):esc(x[c])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function renderTree(){const cats=source('categories'),sorted=id=>cats.filter(x=>x.parent_id===id).sort((a,b)=>a.order-b.order),allParentOptions=(current)=>['<option value="">— Racine —</option>',...cats.filter(x=>x.id!==current.id).map(x=>`<option value="${esc(x.id)}" ${x.id===current.parent_id?'selected':''}>${esc(`${x.id} — ${x.label}`)}</option>`)].join(''),node=x=>`<li><div class="tree-row"><strong>${esc(`${x.id} — ${x.label}`)}</strong><select data-parent-id="${esc(x.id)}">${allParentOptions(x)}</select><button data-tree-add="${esc(x.id)}">＋ enfant</button><button data-tree-move="${esc(x.id)}" data-d="-1">↑</button><button data-tree-move="${esc(x.id)}" data-d="1">↓</button><button data-tree-delete="${esc(x.id)}">×</button></div>${sorted(x.id).length?`<ul>${sorted(x.id).map(node).join('')}</ul>`:''}</li>`;$('#workspace').innerHTML=`<div class="tree"><h3>Hiérarchie des catégories</h3><p><button class="btn" data-tree-add="">＋ Ajouter une catégorie racine</button></p><ul>${sorted(null).map(node).join('')}</ul></div>`;bindTree();}
function bindTree(){const cats=source('categories');document.querySelectorAll('[data-parent-id]').forEach(s=>s.onchange=()=>{const x=cats.find(c=>c.id===s.dataset.parentId);if(x){x.parent_id=s.value||null;markDirty();renderTree();}});document.querySelectorAll('[data-tree-add]').forEach(b=>b.onclick=()=>{let n=1,id;do{id=`CAT_NEW_${n++}`}while(cats.some(x=>x.id===id));const parent=b.dataset.treeAdd||null;cats.push({id,label:'Nouvelle catégorie',short_label:'Nouveau',parent_id:parent,order:(cats.filter(x=>x.parent_id===parent).length+1)*10,icon:'folder',image:'',active:true,description:''});markDirty();renderTree();});document.querySelectorAll('[data-tree-delete]').forEach(b=>b.onclick=()=>{const id=b.dataset.treeDelete;if(cats.some(x=>x.parent_id===id)){alert('Supprimer ou déplacer d’abord les catégories filles.');return;}const i=cats.findIndex(x=>x.id===id);if(i>=0){cats.splice(i,1);markDirty();renderTree();}});document.querySelectorAll('[data-tree-move]').forEach(b=>b.onclick=()=>{const x=cats.find(c=>c.id===b.dataset.treeMove);if(!x)return;const siblings=cats.filter(c=>c.parent_id===x.parent_id).sort((a,b)=>a.order-b.order),i=siblings.indexOf(x),j=i+Number(b.dataset.d);if(j<0||j>=siblings.length)return;[siblings[i].order,siblings[j].order]=[siblings[j].order,siblings[i].order];markDirty();renderTree();});}
function renderRaw(){$('#workspace').innerHTML=`<textarea id="rawEditor" class="raw">${esc(JSON.stringify(S.data,null,2))}</textarea><p><button class="btn" id="rawApply">Appliquer le JSON brut</button></p>`;$('#rawApply').onclick=()=>{try{const o=JSON.parse($('#rawEditor').value);S.data=o;S.items=o.Data?.[S.cfg.collection]||[];markDirty();renderAll();}catch(e){alert('JSON invalide : '+e.message)}}}
load().catch(e=>{$('#workspace').innerHTML=`<p class="semantic-invalid">Erreur de chargement : ${esc(e.message)}. Utiliser un serveur HTTP local.</p>`});
})();
