import { TableWiz } from './table-wiz.js';
const clone=(value)=>structuredClone(value);
const pathJoin=(base,key)=>base?`${base}.${key}`:String(key);
function parseValue(text,sample){if(typeof sample==='number')return Number(text);if(typeof sample==='boolean')return text==='true';if(sample===null)return text===''?null:text;return text;}
function countItems(value){if(Array.isArray(value))return value.length;if(value&&typeof value==='object')return Object.keys(value).length;return 1;}
export class JsonStudio{
  constructor({data=null,schema=null,validator=null,resolver=null,saveAdapter=null,table=null}={}){this.data=clone(data);this.original=clone(data);this.schema=schema;this.validator=validator;this.resolver=resolver;this.saveAdapter=saveAdapter;this.table=table??new TableWiz();this.view='raw';}
  setData(data,{resetOriginal=false}={}){this.data=clone(data);if(resetOriginal)this.original=clone(data);return this;} setView(view){this.view=view;return this;} get(path=null){if(!path)return clone(this.data);return clone(path.split('.').reduce((acc,key)=>acc?.[/^\d+$/.test(key)?Number(key):key],this.data));}
  set(path,value){const keys=path.split('.');const last=keys.pop();let cursor=this.data;for(const key of keys){const k=/^\d+$/.test(key)?Number(key):key;cursor[k]??={};cursor=cursor[k];}cursor[/^\d+$/.test(last)?Number(last):last]=clone(value);return this;}
  move(path,fromIndex,toIndex){const array=this.get(path);if(!Array.isArray(array))throw new Error(`Path is not an array: ${path}`);const[item]=array.splice(fromIndex,1);array.splice(toIndex,0,item);this.set(path,array);return this;} add(path,value){const array=this.get(path);if(!Array.isArray(array))throw new Error(`Path is not an array: ${path}`);array.push(clone(value));this.set(path,array);return this;} remove(path,index){const array=this.get(path);if(!Array.isArray(array))throw new Error(`Path is not an array: ${path}`);array.splice(index,1);this.set(path,array);return this;}
  raw(space=2){return JSON.stringify(this.data,null,space);} importRaw(text){this.data=JSON.parse(text);return this;} exportRaw(space=2){return this.raw(space);} exportSlice({path=null,index=null,key=null}={}){let value=path?this.get(path):clone(this.data);if(index!=null&&Array.isArray(value))value=value[index];if(key!=null&&value&&typeof value==='object')value=value[key];return JSON.stringify(value,null,2);}
  diff(){const changes=[];const walk=(before,after,path='')=>{if(Object.is(before,after))return;if(before===undefined){changes.push({type:'added',path,before,after});return;}if(after===undefined){changes.push({type:'removed',path,before,after});return;}if(!before||!after||typeof before!=='object'||typeof after!=='object'||Array.isArray(before)!==Array.isArray(after)){changes.push({type:'changed',path,before,after});return;}const keys=new Set([...Object.keys(before),...Object.keys(after)]);for(const key of keys)walk(before[key],after[key],pathJoin(path,key));};walk(this.original,this.data);return changes;}
  async validate(context={}){if(!this.validator)return{valid:true,errors:0,warnings:0,issues:[],skipped:true};if(context.collection&&Array.isArray(this.data)&&this.validator.validateCollectionData)return this.validator.validateCollectionData(context.collection,this.data);if(context.collection&&!Array.isArray(this.data)&&this.validator.validateRecord)return this.validator.validateRecord(context.collection,this.data);if(this.validator.validate)return this.validator.validate(this.data,{schema:this.schema,...context});return{valid:true,errors:0,warnings:0,issues:[],skipped:true};}
  async resolved(context={}){if(!this.resolver||!context.collection)return clone(this.data);if(Array.isArray(this.data))return Promise.all(this.data.map(record=>this.resolver.resolveRecord(context.collection,record)));return this.resolver.resolveRecord(context.collection,this.data);} async save(context={}){if(!this.saveAdapter)throw new Error('No save adapter configured');return this.saveAdapter.save(clone(this.data),context);}
  #treeNode(value,key,path,depth=0){const details=document.createElement('details');details.open=depth<2;details.className='nlab-json-tree-node';const summary=document.createElement('summary');summary.innerHTML=`<strong>${key}</strong> <small>${Array.isArray(value)?'array':typeof value} · ${countItems(value)} item${countItems(value)>1?'s':''}</small>`;details.append(summary);if(value&&typeof value==='object'){const body=document.createElement('div');body.style.paddingLeft='1rem';for(const[k,v]of Object.entries(value))body.append(this.#treeNode(v,k,pathJoin(path,k),depth+1));details.append(body);}else{const val=document.createElement('code');val.textContent=JSON.stringify(value);val.style.marginLeft='1rem';details.append(val);}return details;}
  #formNode(value,key,path,depth=0){const wrap=document.createElement('section');wrap.className='nlab-json-form-section';if(value&&typeof value==='object'){const details=document.createElement('details');details.open=depth<2;const summary=document.createElement('summary');summary.innerHTML=`<strong>${key}</strong> <small>${Array.isArray(value)?'liste':'objet'} · ${countItems(value)} item${countItems(value)>1?'s':''}</small>`;details.append(summary);const body=document.createElement('div');body.className='nlab-json-form-body';for(const[k,v]of Object.entries(value))body.append(this.#formNode(v,k,pathJoin(path,k),depth+1));if(Array.isArray(value)){const add=document.createElement('button');add.type='button';add.textContent='+ Ajouter un item';add.addEventListener('click',()=>{const arr=this.get(path);arr.push('');this.set(path,arr);this.render(this._container,{view:'form'});});body.append(add);}details.append(body);wrap.append(details);return wrap;}const label=document.createElement('label');label.className='nlab-json-form-field';const name=document.createElement('span');name.innerHTML=`<strong>${key}</strong> <small>${typeof value}</small>`;let input;if(typeof value==='boolean'){input=document.createElement('select');input.innerHTML='<option value="true">true</option><option value="false">false</option>';input.value=String(value);}else if(typeof value==='string'&&value.length>90){input=document.createElement('textarea');input.rows=4;input.value=value;}else{input=document.createElement('input');input.type=typeof value==='number'?'number':'text';input.value=value??'';}input.addEventListener('change',()=>this.set(path,parseValue(input.value,value)));label.append(name,input);wrap.append(label);return wrap;}
  render(container,{view=this.view,context={}}={}){if(!container||!globalThis.document)return;this._container=container;container.replaceChildren();if(view==='raw'){const textarea=document.createElement('textarea');textarea.value=this.raw();textarea.addEventListener('change',()=>this.importRaw(textarea.value));container.append(textarea);return;}if(view==='table'&&Array.isArray(this.data)){this.table.render(container,this.data);return;}if(view==='tree'){const tools=document.createElement('div');tools.className='demo-controls';tools.innerHTML='<button type="button" data-tree-open>Tout déplier</button><button type="button" data-tree-close>Tout replier</button><label>Niveau <input type="range" min="1" max="6" value="2" data-tree-depth><output>2</output></label>';const root=document.createElement('div');root.className='nlab-json-tree';root.append(this.#treeNode(this.data,'root','',0));container.append(tools,root);tools.querySelector('[data-tree-open]').onclick=()=>root.querySelectorAll('details').forEach(d=>d.open=true);tools.querySelector('[data-tree-close]').onclick=()=>root.querySelectorAll('details').forEach(d=>d.open=false);tools.querySelector('[data-tree-depth]').oninput=e=>{const depth=Number(e.target.value);e.target.nextElementSibling.textContent=String(depth);root.querySelectorAll('details').forEach(d=>{let n=d,p=0;while((n=n.parentElement?.closest('details')))p++;d.open=p<depth;});};return;}if(view==='form'&&this.data&&typeof this.data==='object'){const tools=document.createElement('div');tools.className='demo-controls';tools.innerHTML='<button type="button" data-form-open>Tout déplier</button><button type="button" data-form-close>Tout replier</button>';const form=document.createElement('div');form.className='nlab-json-form';form.append(this.#formNode(this.data,'root','',0));container.append(tools,form);tools.querySelector('[data-form-open]').onclick=()=>form.querySelectorAll('details').forEach(d=>d.open=true);tools.querySelector('[data-form-close]').onclick=()=>form.querySelectorAll('details').forEach(d=>d.open=false);return;}const pre=document.createElement('pre');pre.textContent=this.raw();container.append(pre);}
}
