import { TableWiz } from './table-wiz.js';
const BAD=new Set(['__proto__','prototype','constructor']);
const VIEWS=new Set(['raw','table','tree','form']);
const DISPLAY_MODES=new Set(['label','id','id+label','object']);
const obj=v=>!!v&&typeof v==='object'&&!Array.isArray(v);
const cp=v=>v===undefined?undefined:structuredClone(v);
const join=(p,k)=>p?`${p}.${k}`:String(k);
const key=p=>/^\d+$/.test(p)?Number(p):p;
const parts=p=>{if(p==null||p==='')return[];const a=(Array.isArray(p)?p:String(p).split('.')).filter(x=>x!=='').map(String);if(a.some(x=>BAD.has(x)))throw new JsonStudioError('Unsafe JSON path','UNSAFE_PATH',{path:String(p)});return a};
const same=(a,b)=>{try{return Object.is(a,b)||JSON.stringify(a)===JSON.stringify(b)}catch{return false}};
const count=v=>Array.isArray(v)?v.length:obj(v)?Object.keys(v).length:1;
const read=(value,path)=>{if(path==null||path==='')return value;let current=value;for(const part of parts(path))current=current?.[key(part)];return current};
const issueCount=(issues,level)=>issues.filter(issue=>issue?.level===level).length;
const displayMode=value=>DISPLAY_MODES.has(String(value??'label').toLowerCase())?String(value??'label').toLowerCase():'label';
export class JsonStudioError extends Error{constructor(message,code='JSON_STUDIO_ERROR',details=null){super(message);this.name='JsonStudioError';this.code=code;this.details=details}}
export class JsonStudio{
 constructor({data=null,schema=null,validator=null,resolver=null,saveAdapter=null,table=null,historyLimit=100}={}){this.data=cp(data);this.original=cp(data);this.schema=schema;this.validator=validator;this.resolver=resolver;this.saveAdapter=saveAdapter;this.table=table??new TableWiz();this.view='raw';this.historyLimit=Math.max(1,Number(historyLimit)||100);this.history=[];this.future=[];this.lastError=null}
 setData(data,{resetOriginal=false,recordHistory=false,label='setData'}={}){const n=cp(data);if(recordHistory)this._commit(n,label);else{this.data=n;this.history=[];this.future=[]}if(resetOriginal)this.original=cp(n);this.lastError=null;return this}
 setView(v){this.view=VIEWS.has(String(v))?String(v):'raw';return this}
 get(path=null){let c=this.data;for(const p of parts(path))c=c?.[key(p)];return cp(c)}
 set(path,value,{label='set'}={}){const ps=parts(path);if(!ps.length)return this.setData(value,{recordHistory:true,label});const n=cp(this.data);let c=n;for(let i=0;i<ps.length-1;i++){const k=key(ps[i]),next=key(ps[i+1]);if(c[k]==null)c[k]=typeof next==='number'?[]:{};if(!c[k]||typeof c[k]!=='object')throw new JsonStudioError('Path crosses a primitive','INVALID_PATH',{path:String(path)});c=c[k]}c[key(ps.at(-1))]=cp(value);this._commit(n,label,{path:String(path)});return this}
 unset(path){const ps=parts(path);if(!ps.length)return this.setData(null,{recordHistory:true,label:'unset'});const n=cp(this.data);let c=n;for(let i=0;i<ps.length-1;i++){c=c?.[key(ps[i])];if(!c||typeof c!=='object')return this}const k=key(ps.at(-1));if(Array.isArray(c)&&typeof k==='number'){if(k>=c.length)return this;c.splice(k,1)}else if(c&&Object.hasOwn(c,k))delete c[k];else return this;this._commit(n,'unset',{path:String(path)});return this}
 transaction(fn,{label='transaction'}={}){if(typeof fn!=='function')throw new TypeError('transaction mutator must be a function');const d=cp(this.data),r=fn(d);if(r&&typeof r.then==='function')throw new JsonStudioError('Async transactions are not supported','ASYNC_TRANSACTION_UNSUPPORTED');this._commit(r===undefined?d:cp(r),label);return this}
 _array(path){const a=this.get(path);if(!Array.isArray(a))throw new JsonStudioError(`Path is not an array: ${path}`,'NOT_AN_ARRAY',{path:String(path)});return a}
 add(path,value,{index=null}={}){const a=this._array(path);if(index==null)a.push(cp(value));else{const i=Number(index);if(!Number.isInteger(i)||i<0||i>a.length)throw new JsonStudioError('Array index out of range','INVALID_ARRAY_INDEX');a.splice(i,0,cp(value))}return this.set(path,a,{label:'add'})}
 remove(path,index){const a=this._array(path),i=Number(index);if(!Number.isInteger(i)||i<0||i>=a.length)throw new JsonStudioError('Array index out of range','INVALID_ARRAY_INDEX');a.splice(i,1);return this.set(path,a,{label:'remove'})}
 move(path,from,to){const a=this._array(path),f=Number(from),t=Number(to);if(!Number.isInteger(f)||!Number.isInteger(t)||f<0||f>=a.length||t<0||t>a.length)throw new JsonStudioError('Array index out of range','INVALID_ARRAY_INDEX');const[x]=a.splice(f,1);a.splice(Math.min(t,a.length),0,x);return this.set(path,a,{label:'move'})}
 raw(space=2){return JSON.stringify(this.data,null,space)} exportRaw(space=2){return this.raw(space)}
 importRaw(text,{resetOriginal=false}={}){try{const n=JSON.parse(String(text));this._commit(n,'importRaw');if(resetOriginal)this.original=cp(n);this.lastError=null}catch(e){this.lastError={code:'INVALID_JSON',stage:'import',message:e?.message??String(e)}}return this}
 exportSlice({path=null,index=null,key:nullKey=null,space=2}={}){let v=path==null?cp(this.data):this.get(path);if(index!=null&&Array.isArray(v))v=v[index];if(nullKey!=null&&v&&typeof v==='object')v=v[nullKey];return JSON.stringify(v,null,space)}
 diff({from=this.original,to=this.data}={}){const out=[];const walk=(a,b,p='')=>{if(Object.is(a,b))return;if(a===undefined)return out.push({type:'added',path:p,before:a,after:cp(b)});if(b===undefined)return out.push({type:'removed',path:p,before:cp(a),after:b});if(a===null||b===null||typeof a!=='object'||typeof b!=='object'||Array.isArray(a)!==Array.isArray(b))return out.push({type:'changed',path:p,before:cp(a),after:cp(b)});for(const k of new Set([...Object.keys(a),...Object.keys(b)]))walk(a[k],b[k],join(p,k))};walk(from,to);return out}
 historyState(){return{canUndo:!!this.history.length,canRedo:!!this.future.length,undoCount:this.history.length,redoCount:this.future.length,limit:this.historyLimit,nextUndo:this.history.at(-1)?.label??null,nextRedo:this.future.at(-1)?.label??null}}
 undo(){const e=this.history.pop();if(e){this.future.push({label:e.label,data:cp(this.data)});this.data=cp(e.before);this.lastError=null}return this}
 redo(){const e=this.future.pop();if(e){this.history.push({label:e.label,before:cp(this.data)});this._trim();this.data=cp(e.data);this.lastError=null}return this}
 clearHistory(){this.history=[];this.future=[];return this} markOriginal(){this.original=cp(this.data);return this} resetToOriginal(){this._commit(cp(this.original),'resetToOriginal');return this}
 async validate(context={}){if(!this.validator)return{valid:true,errors:0,warnings:0,issues:[],checked:0,skipped:true};if(context.collection&&typeof this.validator.validateCollectionData==='function')return this.validator.validateCollectionData(context.collection,cp(this.data),context);if(context.collection&&typeof this.validator.validateRecord==='function'){if(Array.isArray(this.data)){const records=[],issues=[];for(let index=0;index<this.data.length;index+=1){const report=await this.validator.validateRecord(context.collection,cp(this.data[index]),{recordIndex:index});records.push(report);issues.push(...(report?.issues??[]))}const errors=issueCount(issues,'error'),warnings=issueCount(issues,'warning');return{valid:errors===0,errors,warnings,issues,checked:this.data.length,records,source:'buffer'}}return this.validator.validateRecord(context.collection,cp(this.data),{recordIndex:context.recordIndex??null})}if(typeof this.validator.validate==='function')return this.validator.validate(cp(this.data),{schema:this.schema,...context});return{valid:true,errors:0,warnings:0,issues:[],checked:0,skipped:true,reason:'DIRECT_DATA_VALIDATION_UNSUPPORTED'}}
 async resolved(context={}){if(!this.resolver||!context.collection)return cp(this.data);if(typeof this.resolver.resolveRecord!=='function')throw new JsonStudioError('Resolver must implement resolveRecord()','RESOLVER_CONTRACT_REQUIRED');if(Array.isArray(this.data))return Promise.all(this.data.map(record=>this.resolver.resolveRecord(context.collection,cp(record))));return this.resolver.resolveRecord(context.collection,cp(this.data))}
 displayResolvedValue(raw,resolved,mapping={}){const map=obj(mapping)?mapping:{};if(Array.isArray(raw)||Array.isArray(resolved)){const rawList=Array.isArray(raw)?raw:[],resolvedList=Array.isArray(resolved)?resolved:[];const length=Math.max(rawList.length,resolvedList.length);return Array.from({length},(_,index)=>this.displayResolvedValue(rawList[index],resolvedList[index],map))}const mode=displayMode(map.mode);if(mode==='object')return resolved==null?cp(raw):cp(resolved);const idField=cleanDisplayField(map.idField,'id'),labelFields=displayLabelFields(map);const id=resolved&&typeof resolved==='object'?read(resolved,idField)??raw:raw;let label=null;if(resolved&&typeof resolved==='object'){for(const field of labelFields){const candidate=read(resolved,field);if(candidate!==undefined&&candidate!==null&&candidate!==''){label=candidate;break}}}if(label==null||label==='')label=id??raw??'';if(mode==='id')return id??'';if(mode==='id+label'){const left=String(id??''),right=String(label??'');if(!left)return right;if(!right||left===right)return left;return `${left}${String(map.separator??' — ')}${right}`}return label}
 mapResolvedRecord(resolution,{mappings={}}={}){if(!obj(resolution)||!obj(resolution.data)||!obj(resolution.resolved))return{data:cp(resolution?.data??resolution),resolved:cp(resolution?.resolved??{}),display:cp(resolution?.data??resolution),issues:cp(resolution?.issues??[])};const display=cp(resolution.data);const specs=obj(mappings)?mappings:{};for(const[field,value]of Object.entries(resolution.resolved)){const raw=resolution.data[field],mapping=obj(specs[field])?specs[field]:{};display[field]=this.displayResolvedValue(raw,value,mapping)}return{...cp(resolution),display}}
 async resolvedDisplay(context={},options={}){const value=await this.resolved(context);return Array.isArray(value)?value.map(entry=>this.mapResolvedRecord(entry,options)):this.mapResolvedRecord(value,options)}
 async save(context={}){if(!this.saveAdapter)throw new JsonStudioError('No save adapter configured','SAVE_ADAPTER_REQUIRED');return this.saveAdapter.save(cp(this.data),context)}
 _commit(next,label){const n=cp(next);if(same(this.data,n))return false;this.history.push({label:String(label),before:cp(this.data)});this._trim();this.data=n;this.future=[];this.lastError=null;return true} _trim(){if(this.history.length>this.historyLimit)this.history.splice(0,this.history.length-this.historyLimit)}
 render(container,{view=this.view,document:doc=container?.ownerDocument??globalThis.document}={}){if(!container||!doc?.createElement)return null;this._container=container;this.setView(view);container.replaceChildren?.();if(this.view==='raw')return this._rawView(container,doc);if(this.view==='table'&&Array.isArray(this.data)){this.table?.render?.(container,this.data);return container}if(this.view==='tree')return this._treeView(container,doc);if(this.view==='form'&&this.data&&typeof this.data==='object')return this._formView(container,doc);const pre=doc.createElement('pre');pre.textContent=this.raw();container.append?.(pre);return container}
 _rawView(c,d){const t=d.createElement('textarea');t.value=this.raw();t.setAttribute?.('aria-label','JSON brut');t.addEventListener?.('change',()=>{this.importRaw(t.value);if(this.lastError){t.setAttribute?.('aria-invalid','true');t.setAttribute?.('title',this.lastError.message)}else{t.removeAttribute?.('aria-invalid');t.removeAttribute?.('title');t.value=this.raw()}});c.append?.(t);return c}
 _treeView(c,d){const root=d.createElement('div');root.className='nlab-json-tree';root.append?.(this._treeNode(d,this.data,'root',[],0));c.append?.(this._tools(d,root,true),root);return c}
 _formView(c,d){const root=d.createElement('div');root.className='nlab-json-form';root.append?.(this._formNode(d,this.data,'root',[],0));c.append?.(this._tools(d,root,false),root);return c}
 _tools(d,root,depth){const box=d.createElement('div');box.className='nlab-json-studio-tools';const open=d.createElement('button'),close=d.createElement('button');open.type=close.type='button';open.textContent='Tout déplier';close.textContent='Tout replier';open.addEventListener?.('click',()=>this._details(root).forEach(x=>x.open=true));close.addEventListener?.('click',()=>this._details(root).forEach(x=>x.open=false));box.append?.(open,close);if(depth){const range=d.createElement('input'),out=d.createElement('output');range.type='range';range.min='1';range.max='6';range.value='2';out.textContent='2';range.addEventListener?.('input',()=>{const n=Math.max(1,Number(range.value)||1);out.textContent=String(n);this._details(root).forEach(x=>x.open=this._depth(x,root)<n)});box.append?.(range,out)}return box}
 _summary(d,keyName,value,kind=null){const s=d.createElement('summary'),b=d.createElement('strong'),m=d.createElement('small');b.textContent=String(keyName);const n=count(value),type=kind??(Array.isArray(value)?'array':value===null?'null':typeof value);m.textContent=` ${type} · ${n} item${n>1?'s':''}`;s.append?.(b,m);return s}
 _treeNode(d,v,k,p,depth){const det=d.createElement('details');det.open=depth<2;det.className='nlab-json-tree-node';det.setAttribute?.('data-json-path',p.join('.'));det.append?.(this._summary(d,k,v));if(v&&typeof v==='object'){const body=d.createElement('div');body.style.paddingLeft='1rem';for(const[ck,cv]of Object.entries(v))body.append?.(this._treeNode(d,cv,ck,[...p,String(ck)],depth+1));det.append?.(body)}else{const code=d.createElement('code');code.textContent=JSON.stringify(v);det.append?.(code)}return det}
 _formNode(d,v,k,p,depth){const wrap=d.createElement('section');wrap.className='nlab-json-form-section';const pathText=p.join('.');wrap.setAttribute?.('data-json-path',pathText);if(v&&typeof v==='object'){const det=d.createElement('details'),body=d.createElement('div');det.open=depth<2;det.append?.(this._summary(d,k,v,Array.isArray(v)?'liste':'objet'));for(const[ck,cv]of Object.entries(v))body.append?.(this._formNode(d,cv,ck,[...p,String(ck)],depth+1));if(Array.isArray(v)){const add=d.createElement('button');add.type='button';add.textContent='+ Ajouter un item';add.addEventListener?.('click',()=>{this.add(p,'');this.render(this._container,{view:'form',document:d})});body.append?.(add)}det.append?.(body);wrap.append?.(det);return wrap}const label=d.createElement('label'),name=d.createElement('span'),strong=d.createElement('strong'),meta=d.createElement('small');strong.textContent=String(k);meta.textContent=` ${v===null?'null':typeof v}`;name.append?.(strong,meta);let input;if(typeof v==='boolean'){input=d.createElement('select');for(const x of['true','false']){const o=d.createElement('option');o.value=x;o.textContent=x;input.append?.(o)}input.value=String(v)}else if(typeof v==='string'&&v.length>90){input=d.createElement('textarea');input.rows=4;input.value=v}else{input=d.createElement('input');input.type=typeof v==='number'?'number':'text';input.value=v??''}input.setAttribute?.('data-json-input',pathText);input.addEventListener?.('change',()=>{const r=this._parse(input.value,v);if(!r.ok){input.setAttribute?.('aria-invalid','true');input.setAttribute?.('title',r.message);return}input.removeAttribute?.('aria-invalid');input.removeAttribute?.('title');this.set(p,r.value,{label:'form-edit'})});label.append?.(name,input);wrap.append?.(label);return wrap}
 _parse(text,sample){if(typeof sample==='number'){const n=Number(text);return text!==''&&Number.isFinite(n)?{ok:true,value:n}:{ok:false,message:'Nombre invalide.'}}if(typeof sample==='boolean')return{ok:true,value:String(text)==='true'};if(sample===null)return{ok:true,value:text===''?null:text};return{ok:true,value:text}}
 _details(root){if(root?.querySelectorAll)return[...root.querySelectorAll('details')];const out=[];const walk=n=>{for(const c of n?.children??[]){if(c?.tagName==='DETAILS')out.push(c);walk(c)}};walk(root);return out}
 _depth(det,root){let n=0,c=det?.parentElement;while(c&&c!==root){if(c.tagName==='DETAILS')n++;c=c.parentElement}return n}
}
function cleanDisplayField(value,fallback){const field=String(value??fallback).trim();parts(field);return field||fallback}
function displayLabelFields(mapping){if(Array.isArray(mapping.labelFields)&&mapping.labelFields.length)return mapping.labelFields.map(field=>cleanDisplayField(field,'label'));if(mapping.labelField)return[cleanDisplayField(mapping.labelField,'label')];return['label','name','title','id']}
