(()=>{
  const q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>[...r.querySelectorAll(s)];
  function icon(name){return window.NLabIcons?.get(name)||''}
  function initFoldables(root=document){qa('details.nlab-fold',root).forEach(d=>{if(d.dataset.nlabReady)return;d.dataset.nlabReady='1';d.dataset.defaultOpen=d.open?'1':'0'})}
  function setFoldState(state,root=document){const folds=qa('details.nlab-fold',root);folds.forEach(d=>{if(state==='open')d.open=true;else if(state==='closed')d.open=false;else d.open=d.dataset.defaultOpen==='1'})}
  function initToolbar(root=document){const host=q('[data-nlab-toolbar]',root);if(!host||host.dataset.nlabReady)return;host.dataset.nlabReady='1';host.innerHTML=`<button class="nlab-ui-control" data-tool="anchor" title="Déplacer">${icon('anchor')}</button><button class="nlab-ui-control" data-tool="fold" title="État par défaut">${icon('default_state')}</button><button class="nlab-ui-control" data-tool="help" title="Aide">${icon('help')}</button><button class="nlab-ui-control" data-tool="top" title="Retour en haut">${icon('scroll_top')}</button><button class="nlab-ui-control" data-tool="lock" title="Verrouiller">${icon('lock')}</button><button class="nlab-ui-control" data-tool="more" title="Réduire">${icon('more')}</button>`;
    Object.assign(host.style,{position:'fixed',right:'14px',bottom:'14px',display:'flex',gap:'5px',padding:'6px',zIndex:'100'});host.classList.add('nlab-card');
    let foldState=0;const fold=q('[data-tool="fold"]',host);fold?.addEventListener('click',()=>{foldState=(foldState+1)%3;const states=['default','open','closed'];const names=['default_state','expand','collapse'];setFoldState(states[foldState],root);fold.innerHTML=icon(names[foldState])});
    q('[data-tool="top"]',host)?.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}));
    q('[data-tool="help"]',host)?.addEventListener('click',()=>window.NLabHelp?.toggle?.('global'));
  }
  function initHelp(root=document){const host=q('[data-nlab-help-panel]',root);if(!host||host.dataset.nlabReady)return;host.dataset.nlabReady='1';host.innerHTML=`<div style="display:flex;align-items:center;gap:8px;padding:10px 12px;border-bottom:1px solid var(--nlab-line)"><button class="nlab-ui-control" data-help-anchor>${icon('anchor')}</button><strong style="flex:1">Aide contextuelle</strong><button class="nlab-ui-control" data-help-reset>${icon('reset')}</button><button class="nlab-ui-control" data-help-close>${icon('close')}</button></div><div data-help-body style="padding:14px;overflow:auto">Sélectionnez une aide contextuelle.</div>`;Object.assign(host.style,{position:'fixed',right:'14px',top:'84px',width:'min(420px,calc(100vw - 28px))',maxHeight:'70vh',display:'none',zIndex:'110'});host.classList.add('nlab-card');const body=q('[data-help-body]',host);const close=()=>host.style.display='none';const open=(id='global',content)=>{body.textContent=content||`Aide : ${id}`;host.style.display='block'};q('[data-help-close]',host)?.addEventListener('click',close);q('[data-help-reset]',host)?.addEventListener('click',()=>{host.style.right='14px';host.style.top='84px'});qa('[data-help-id]',root).forEach(b=>b.addEventListener('click',e=>{e.preventDefault();open(b.dataset.helpId,b.dataset.helpText)}));window.NLabHelp={open,close,toggle:(id='global')=>host.style.display==='block'?close():open(id)}
  }
  function boot(root=document){initFoldables(root);initHelp(root);initToolbar(root)}
  window.NLabUI={boot,setFoldState};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>boot());else boot();
})();
